ASSESSMENT_QUESTIONS = [
    "What symptoms are bothering you the most right now?",
    "When did your symptoms first start?",
    "How have your symptoms changed over time?",
    "Do you have fever or chills? Describe details and temperature if known.",
    "Are you coughing? Describe frequency, triggers, and sputum if present.",
    "Do you feel shortness of breath? When does it occur?",
    "Do you have chest pain or pressure? Describe location and character.",
    "Have you noticed rapid heartbeat or palpitations?",
    "Do you feel unusual fatigue? How does it affect daily activity?",
    "Have you lost weight unintentionally recently?",
    "Do you experience night sweats?",
    "Do you have headaches? Describe type, location, and pattern.",
    "Have you had a sudden severe headache unlike usual?",
    "Do you feel dizzy or lightheaded?",
    "Have you had fainting episodes?",
    "Any confusion, concentration issues, or disorientation?",
    "Any speech changes or trouble speaking?",
    "Any one-sided weakness in face, arm, or leg?",
    "Any vision changes (blurred, double vision, vision loss)?",
    "Do you have neck stiffness or neck pain?",
    "Any nausea? What seems to trigger it?",
    "Any vomiting? How often and what does it look like?",
    "Any diarrhea? For how long and how frequent?",
    "Any constipation? How long has it lasted?",
    "Describe any abdominal pain (location, severity, relation to meals).",
    "Any blood in stool or black stools?",
    "Any burning/pain during urination?",
    "Any frequent urination, urgency, or nighttime urination?",
    "Any blood in urine or urine color changes?",
    "Any back pain? Where exactly and what worsens it?",
    "Any joint pain or swelling? Which joints are affected?",
    "Any muscle pain or cramps?",
    "Any skin rash or skin changes?",
    "Any swelling in legs, ankles, or feet?",
    "Any leg pain while walking or at rest?",
    "Any numbness or tingling? Where and when?",
    "How has your sleep been recently?",
    "Any anxiety, panic episodes, or high stress?",
    "Any low mood, sadness, or loss of interest?",
    "How is your appetite compared to usual?",
    "Any increased thirst or dry mouth?",
    "Do you feel unusually heat-intolerant?",
    "Do you feel unusually cold-intolerant?",
    "Any sore throat, ear pain, or sinus pressure?",
    "Any recent contact with sick people, travel, or infection exposure?",
]
